-- 1. Add Stock Management columns to products table if not exists
ALTER TABLE products ADD COLUMN IF NOT EXISTS track_stock BOOLEAN DEFAULT FALSE;
ALTER TABLE products ADD COLUMN IF NOT EXISTS stock_quantity INTEGER DEFAULT 0;

-- 2. Create Expenses Table
CREATE TABLE IF NOT EXISTS expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  category TEXT NOT NULL, -- e.g. 'Rent', 'Salaries', 'Ingredients', 'Utilities', 'Other'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. Enable Row Level Security (RLS) & Policies for Expenses
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'expenses' AND policyname = 'Public expenses select'
    ) THEN
        CREATE POLICY "Public expenses select" ON expenses FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'expenses' AND policyname = 'Public expenses insert'
    ) THEN
        CREATE POLICY "Public expenses insert" ON expenses FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'expenses' AND policyname = 'Public expenses update'
    ) THEN
        CREATE POLICY "Public expenses update" ON expenses FOR UPDATE USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'expenses' AND policyname = 'Public expenses delete'
    ) THEN
        CREATE POLICY "Public expenses delete" ON expenses FOR DELETE USING (true);
    END IF;
END
$$;
