-- 1. Create Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  name_ckb TEXT,
  price NUMERIC NOT NULL,
  category TEXT,
  sub_category TEXT,
  barcode TEXT,
  image_url TEXT
);

-- 2. Create Tables Table (for restaurant tables)
CREATE TABLE IF NOT EXISTS tables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  status TEXT DEFAULT 'available'
);

-- 3. Create Captains Table
CREATE TABLE IF NOT EXISTS captains (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT NOT NULL
);

-- 4. Create Cashiers Table
CREATE TABLE IF NOT EXISTS cashiers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT NOT NULL
);

-- 5. Create Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_id BIGINT REFERENCES tables(id),
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  items JSONB, -- Stores array of items in the order
  total_amount NUMERIC
);

-- 6. Create Sales Table (for paid/completed orders history)
-- You can also just keep them in 'orders' with status='paid', but creating a separate one to match your logic
CREATE TABLE IF NOT EXISTS sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- or use original order id if unique
  original_order_id BIGINT,
  table_id BIGINT,
  status TEXT DEFAULT 'paid',
  paid_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  items JSONB,
  total_amount NUMERIC
);

-- SEED DATA --

-- Products
INSERT INTO products (name, name_ckb, price, category, sub_category, image_url) VALUES
('Double Apple', 'سێوی دوانە', 12000, 'Shisha', 'Double Apple', '/shisha.png'),
('Mint', 'نەعنا', 12000, 'Shisha', 'Mint', '/shisha.png'),
('Lemon', 'لیمۆ', 12000, 'Shisha', 'Lemon', '/shisha.png'),
('Grape', 'ترێ', 12000, 'Shisha', 'Grape', '/shisha.png'),
('Gum', 'بنێشت', 12000, 'Shisha', 'Gum', '/shisha.png'),
('Qazwan Coffee', 'قاوەی قەزوان', 3000, 'Hot Drinks', NULL, 'https://images.unsplash.com/photo-1595434091143-b375ced5fe5c?auto=format&fit=crop&q=80&w=200'),
('Chocolate Coffee', 'قاوەی شۆکۆلاتە', 4000, 'Hot Drinks', NULL, 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=200'),
('Plain Coffee', 'قاوەی سادە', 2000, 'Hot Drinks', NULL, '/plain_coffee.png'),
('Nescafe', 'نیسکافێ', 3000, 'Hot Drinks', NULL, '/nescafe.png'),
('Cappuccino', 'کاپوچینۆ', 4000, 'Hot Drinks', NULL, '/cappuccino.png'),
('Milk', 'شیر', 2000, 'Hot Drinks', NULL, '/milk.png'),
('Tea', 'چا', 500, 'Hot Drinks', NULL, '/tea.png'),
('Orange Juice', 'شەربەتی پرتەقاڵ', 4000, 'Juices', NULL, 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?auto=format&fit=crop&q=80&w=200'),
('Banana Juice', 'شەربەتی مۆز', 4000, 'Juices', NULL, '/banana_juice.png'),
('Melon Juice', 'شەربەتی کاڵەک', 4000, 'Juices', NULL, '/melon_juice.png'),
('Mexican (Mixed)', 'مەکسیکی', 5000, 'Juices', NULL, '/mexican_mixed.png'),
('Pepsi', 'پیپسی', 1000, 'Cold Drinks', NULL, 'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&q=80&w=200'),
('Coca-Cola', 'کۆکاکۆلا', 1000, 'Cold Drinks', NULL, 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=200'),
('Tiger', 'تایگەر', 1000, 'Cold Drinks', NULL, '/tiger.png'),
('Fanta', 'فانتا', 1000, 'Cold Drinks', NULL, 'https://images.unsplash.com/photo-1624517452488-04869289c4ca?auto=format&fit=crop&q=80&w=200'),
('Mountain Dew', 'ماونتێن دیو', 1000, 'Cold Drinks', NULL, '/mountain_dew.png'),
('Mastaw (Doogh)', 'ماستاو', 1500, 'Cold Drinks', NULL, '/mastaw.png'),
('Water', 'ئاو', 500, 'Cold Drinks', NULL, '/water_bottle.png'),
('Ice Cream', 'ئایس کرێم', 5000, 'Dessert', NULL, 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&q=80&w=200'),
('Sweets', 'شیرینی', 5000, 'Dessert', NULL, 'https://images.unsplash.com/photo-1559553156-2e97137af16f?auto=format&fit=crop&q=80&w=200');

-- Tables (1 to 30)
INSERT INTO tables (name, status)
SELECT 'Table ' || generate_series, 'available'
FROM generate_series(1, 30);

-- Captains
INSERT INTO captains (name, code) VALUES
('Captain Jack', '1234'),
('Captain Sarah', '5678');

-- Cashiers
INSERT INTO cashiers (name, code) VALUES
('Cashier Main', '1010');
