CREATE TABLE IF NOT EXISTS cashiers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Seed initial cashiers if table is empty
INSERT INTO cashiers (name, code)
SELECT * FROM (SELECT 'Cashier 1', '1234') AS tmp
WHERE NOT EXISTS (
    SELECT name FROM cashiers WHERE name = 'Cashier 1'
) LIMIT 1;
