-- 1. Create Tables (PostgreSQL Compatible)

-- Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  image_url TEXT,
  description TEXT,
  name_ckb TEXT, -- Kurdish Name Support
  barcode TEXT, -- Barcode scanning support
  is_available BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Captains Table
CREATE TABLE IF NOT EXISTS captains (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Cashiers Table
CREATE TABLE IF NOT EXISTS cashiers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tables (Restaurant Tables)
CREATE TABLE IF NOT EXISTS tables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  captain_id BIGINT REFERENCES captains(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'available', -- 'available' or 'occupied'
  code_pin TEXT, -- Access PIN for the table
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  table_id BIGINT REFERENCES tables(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'pending', -- 'pending', 'paid', 'cancelled', 'voided'
  total DECIMAL(10,2) DEFAULT 0.00,
  payment_method TEXT,
  cashier_id BIGINT REFERENCES cashiers(id) ON DELETE SET NULL, -- Track who closed it
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  paid_at TIMESTAMP WITH TIME ZONE,
  void_reason TEXT
);

-- Order Items Table
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  quantity INTEGER NOT NULL,
  price DECIMAL(10,2) NOT NULL, -- Price at time of order
  note TEXT, -- Special instructions (e.g. "No Sugar")
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);


-- Debts Table
CREATE TABLE IF NOT EXISTS debts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  status TEXT DEFAULT 'unpaid', -- 'unpaid' or 'paid'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);


-- 2. Enable Row Level Security (RLS) & Policies

-- Debts
ALTER TABLE debts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public debts select" ON debts FOR SELECT USING (true);
CREATE POLICY "Public debts insert" ON debts FOR INSERT WITH CHECK (true);
CREATE POLICY "Public debts update" ON debts FOR UPDATE USING (true);
CREATE POLICY "Public debts delete" ON debts FOR DELETE USING (true);

-- Products
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public products select" ON products FOR SELECT USING (true);
CREATE POLICY "Public products insert" ON products FOR INSERT WITH CHECK (true);
CREATE POLICY "Public products update" ON products FOR UPDATE USING (true);
CREATE POLICY "Public products delete" ON products FOR DELETE USING (true);

-- Captains
ALTER TABLE captains ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public captains select" ON captains FOR SELECT USING (true);
CREATE POLICY "Public captains insert" ON captains FOR INSERT WITH CHECK (true);
CREATE POLICY "Public captains update" ON captains FOR UPDATE USING (true);
CREATE POLICY "Public captains delete" ON captains FOR DELETE USING (true);

-- Cashiers
ALTER TABLE cashiers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public cashiers select" ON cashiers FOR SELECT USING (true);
CREATE POLICY "Public cashiers insert" ON cashiers FOR INSERT WITH CHECK (true);
CREATE POLICY "Public cashiers update" ON cashiers FOR UPDATE USING (true);
CREATE POLICY "Public cashiers delete" ON cashiers FOR DELETE USING (true);

-- Tables
ALTER TABLE tables ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public tables select" ON tables FOR SELECT USING (true);
CREATE POLICY "Public tables insert" ON tables FOR INSERT WITH CHECK (true);
CREATE POLICY "Public tables update" ON tables FOR UPDATE USING (true);
CREATE POLICY "Public tables delete" ON tables FOR DELETE USING (true);

-- Orders
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public orders select" ON orders FOR SELECT USING (true);
CREATE POLICY "Public orders insert" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Public orders update" ON orders FOR UPDATE USING (true);
CREATE POLICY "Public orders delete" ON orders FOR DELETE USING (true);

-- Order Items
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public order_items select" ON order_items FOR SELECT USING (true);
CREATE POLICY "Public order_items insert" ON order_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Public order_items update" ON order_items FOR UPDATE USING (true);
CREATE POLICY "Public order_items delete" ON order_items FOR DELETE USING (true);


-- 3. Seed Basic Data (Optional - Only runs if tables are empty)

-- Default Cashier (Pin: 1234)
INSERT INTO cashiers (name, code)
SELECT 'Pharmacist Main', '1234'
WHERE NOT EXISTS (SELECT 1 FROM cashiers LIMIT 1);

-- Default Captain (Pin: 0000)
INSERT INTO captains (name, code)
SELECT 'Captain 1', '0000'
WHERE NOT EXISTS (SELECT 1 FROM captains LIMIT 1);

-- Default Tables
INSERT INTO tables (name, code_pin)
SELECT 'Table 1', '1111' WHERE NOT EXISTS (SELECT 1 FROM tables WHERE name = 'Table 1');
INSERT INTO tables (name, code_pin)
SELECT 'Table 2', '2222' WHERE NOT EXISTS (SELECT 1 FROM tables WHERE name = 'Table 2');
